Refactored code for accessibility
hoolycrash/trainboard pull request #16
Opened 2024-06-04 06:10 UTC by claudiush

- Refactored some part of the CSS to use more flexible variables
- Top right search box is now just one element that is styled for responsive layout
- Have the whole row as a click/tap target (almost, some empty whitespace still left if very long info message are shown)
- Removed duplicate viewport meta tags
- Use semantic <nav> for the nav bar
- Updated train arrival animation to be smoother and better performing by not animating margin

2024-06-04 06:58 UTC, claudiush commented
Just realized that the styling update broke dark mode as it's missing the white colour now

2024-06-04 09:27 UTC, claudiush commented
Dark mode fixed now. 

Also snuck in some optimized graphical assets: Same quality, but reduced file size

2024-06-04 13:00 UTC, hoolycrash requested changes

2024-06-06 09:03 UTC, claudiush commented
Removed the opacity from main screen navbar.

2024-06-06 11:06 UTC, merged